// Generated by CoffeeScript 1.7.1
(function() {
  var BeaconSchema, Schema, appBuilderConn, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  appBuilderConn = mongoose.createConnection('mongodb://localhost:27017/meteor-test');

  BeaconSchema = new Schema({
    _id: false,
    userId: String,
    uuid: String,
    major: Number,
    minor: Number,
    tags: {
      type: String,
      ref: 'Tag'
    },
    notes: String,
    createdAt: Number,
    updatedAt: Number
  });

  module.exports = appBuilderConn.model('Beacon', BeaconSchema);

}).call(this);

//# sourceMappingURL=beacon.map
