// Generated by CoffeeScript 1.7.1
(function() {
  var ContactSchema, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ContactSchema = new Schema({
    _id: false,
    name: String,
    email: String,
    message: String
  });

  module.exports = mongoose.model('Contact', ContactSchema);

}).call(this);

//# sourceMappingURL=contact.map
