// Generated by CoffeeScript 1.7.1
(function() {
  var ContactSchema, Schema, contactsConn, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  contactsConn = mongoose.createConnection('mongodb://localhost:27017/contacts');

  ContactSchema = new Schema({
    _id: false,
    name: String,
    email: String,
    message: String
  });

  module.exports = contactsConn.model('Contact', ContactSchema);

}).call(this);

//# sourceMappingURL=contact.map
