// Generated by CoffeeScript 1.7.1
(function() {
  var LogSchema, Schema, appBuilderConn, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  appBuilderConn = mongoose.createConnection('mongodb://localhost:27017/meteor');

  LogSchema = new Schema({
    _id: false,
    uuid: String,
    appKey: String,
    major: Number,
    minor: Number,
    deviceId: String,
    time: Number
  });

  module.exports = appBuilderConn.model('Log', LogSchema);

}).call(this);

//# sourceMappingURL=log.map
