// Generated by CoffeeScript 1.7.1
(function() {
  var LogSchema, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  LogSchema = new Schema({
    uuid: String,
    major: String,
    minor: String,
    deviceId: String,
    time: Number
  });

  module.exports = mongoose.model('Log', LogSchema);

}).call(this);

//# sourceMappingURL=logs.map
