// Generated by CoffeeScript 1.7.1
(function() {
  var Schema, TagSchema, appBuilderConn, common, config, mongoose;

  mongoose = require('mongoose');

  common = require('../../common');

  config = common.config();

  Schema = mongoose.Schema;

  appBuilderConn = mongoose.createConnection(config.mongo_path);

  TagSchema = new Schema({
    _id: false,
    text: String,
    beacons: {
      type: String,
      ref: 'Beacon'
    },
    userId: String,
    createdAt: Number,
    updatedAt: Number
  });

  module.exports = appBuilderConn.model('Tag', TagSchema);

}).call(this);

//# sourceMappingURL=tag.map
