// Generated by CoffeeScript 1.7.1
(function() {
  var Schema, ZoneSchema, appBuilderConn, common, config, mongoose;

  mongoose = require('mongoose');

  common = require('../../common');

  config = common.config();

  Schema = mongoose.Schema;

  appBuilderConn = mongoose.createConnection(config.mongo_path);

  ZoneSchema = new Schema({
    _id: false,
    text: String,
    beacons: {
      type: String,
      ref: 'Beacon'
    },
    userId: String,
    createdAt: Number,
    updatedAt: Number
  });

  module.exports = appBuilderConn.model('Zone', ZoneSchema);

}).call(this);

//# sourceMappingURL=zone.map
